# Generated by Django 5.0.2 on 2024-03-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_userdatalog_emial_alter_userdatalog_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdatalog',
            old_name='emial',
            new_name='email',
        ),
    ]
